### ISSUE TITLE
BGforge MLS v2.0.0 Server crashes when opening mod folder 

### ISSUE THREAD

**Issue by Roberciiik** [BGforgeNet/VScode-BGforge-MLS#57]
### Description
When opening a folder with a modification (in my case it is NTotSC), there is a VS Code notification about plugin's server crash.

### Console output

```
onInitialize started
workspace_root = c:\<path to mod>\NTotSC
onInitialize completed
onInitialized started
{"errno":-4058,"syscall":"open","code":"ENOENT","path":"c:\\<path to mod>\\NTotSC\\.bgforge.yml"}
initializing translation
tra is not a directory, aborting tra load
initialized
reload filedata file:///c%3A/<path to mod>/NTotSC/ntotsc/ntotsc.tp2
node:fs:2490
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat 'c:\c:'
    at Object.realpathSync (node:fs:2490:7)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:5:4831)
    at li (c:\Users\<user>\.vscode\extensions\bgforge.bgforge-mls-2.0.0\server\out\server.js:167:5395)
    at ws.inWorkspace (c:\Users\<user>\.vscode\extensions\bgforge.bgforge-mls-2.0.0\server\out\server.js:220:3646)
    at ws.displayPath (c:\Users\<user>\.vscode\extensions\bgforge.bgforge-mls-2.0.0\server\out\server.js:220:3710)
    at ws.reloadFileData (c:\Users\<user>\.vscode\extensions\bgforge.bgforge-mls-2.0.0\server\out\server.js:220:4472)
    at Zo.reloadFileData (c:\Users\<user>\.vscode\extensions\bgforge.bgforge-mls-2.0.0\server\out\server.js:223:3109)
    at c:\Users\<user>\.vscode\extensions\bgforge.bgforge-mls-2.0.0\server\out\server.js:228:4643 {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'c:\\c:'
}
[Error - 20:45:27] The BGforge MLS server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by burner1024** [comment]
what's the repo?

**Comment by Roberciiik** [comment]
1. Download NTotSC modification from github: https://github.com/SpellholdStudios/NTotSC and unpack downloaded zip.
2. Right-click on the NTotSC-master folder and select "Open with Code" option
3. Notification shows up after a few seconds that the server crashed.

**Comment by burner1024** [comment]
Try [this build](https://github.com/BGforgeNet/VScode-BGforge-MLS/actions/runs/4000312083)

**Comment by Roberciiik** [comment]
Seems it is a working solution. Closing the issue, thanks!
