### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat 'C:\Users\ALIEN\AppData\Local\Programs\Microsoft VS Code Insiders\undefined'

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/VScode-BGforge-MLS#59]
### Code

```
onInitialize started
onInitialize completed
onInitialized started
{"code":"ERR_INVALID_ARG_TYPE"}
initializing translation
tra is not a directory, aborting tra load
initialized
reload filedata file:///e%3A/Gry-IE/BG2EE-SoS/SoSCre/lib/install-cre.tpa
node:fs:2538
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\ALIEN\AppData\Local\Programs\Microsoft VS Code Insiders\undefined'
    at Object.realpathSync (node:fs:2538:7)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:2:4804)
    at ui (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:167:5422)
    at Ss.inWorkspace (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3646)
    at Ss.displayPath (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3710)
    at Ss.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:4672)
    at nc.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:223:3319)
    at c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:228:4638 {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\Users\\ALIEN\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\undefined'
}
[Info  - 8:29:28 PM] Connection to server got closed. Server will restart.
true
onInitialize started
onInitialize completed
onInitialized started
{"code":"ERR_INVALID_ARG_TYPE"}
initializing translation
tra is not a directory, aborting tra load
initialized
reload filedata file:///e%3A/Gry-IE/BG2EE-SoS/SoSCre/lib/install-cre.tpa
node:fs:2538
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\ALIEN\AppData\Local\Programs\Microsoft VS Code Insiders\undefined'
    at Object.realpathSync (node:fs:2538:7)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:2:4804)
    at ui (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:167:5422)
    at Ss.inWorkspace (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3646)
    at Ss.displayPath (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3710)
    at Ss.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:4672)
    at nc.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:223:3319)
    at c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:228:4638 {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\Users\\ALIEN\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\undefined'
}
[Info  - 8:29:28 PM] Connection to server got closed. Server will restart.
true
onInitialize started
onInitialize completed
onInitialized started
{"code":"ERR_INVALID_ARG_TYPE"}
node:fs:2538
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\ALIEN\AppData\Local\Programs\Microsoft VS Code Insiders\undefined'
    at Object.realpathSync (node:fs:2538:7)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:2:4804)
    at ui (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:167:5422)
    at Ss.inWorkspace (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3646)
    at Ss.displayPath (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3710)
    at Ss.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:4672)
    at nc.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:223:3319)
    at c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:228:4638 {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\Users\\ALIEN\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\undefined'
}
initializing translation
tra is not a directory, aborting tra load
[Info  - 8:29:28 PM] Connection to server got closed. Server will restart.
true
onInitialize started
onInitialize completed
onInitialized started
{"code":"ERR_INVALID_ARG_TYPE"}
node:fs:2538
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\ALIEN\AppData\Local\Programs\Microsoft VS Code Insiders\undefined'
    at Object.realpathSync (node:fs:2538:7)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:2:4804)
    at ui (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:167:5422)
    at Ss.inWorkspace (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3646)
    at Ss.displayPath (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3710)
    at Ss.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:4672)
    at nc.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:223:3319)
    at c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:228:4638 {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\Users\\ALIEN\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\undefined'
}
initializing translation
tra is not a directory, aborting tra load
[Info  - 8:29:31 PM] Connection to server got closed. Server will restart.
true
onInitialize started
onInitialize completed
onInitialized started
{"code":"ERR_INVALID_ARG_TYPE"}
initializing translation
tra is not a directory, aborting tra load
initialized
reload filedata file:///e%3A/Gry-IE/BG2EE-SoS/SoSCre/lib/install-cre.tpa
node:fs:2538
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\ALIEN\AppData\Local\Programs\Microsoft VS Code Insiders\undefined'
    at Object.realpathSync (node:fs:2538:7)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:2:4804)
    at ui (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:167:5422)
    at Ss.inWorkspace (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3646)
    at Ss.displayPath (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:3710)
    at Ss.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:220:4672)
    at nc.reloadFileData (c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:223:3319)
    at c:\Users\ALIEN\.vscode-insiders\extensions\bgforge.bgforge-mls-2.1.2\server\out\server.js:228:4638 {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\Users\\ALIEN\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\undefined'
}
[Error - 8:29:32 PM] The BGforge MLS server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by burner1024** [comment]
So this happens only in insiders build?

**Comment by ALIENQuake** [comment]
Yes, but the insider's code will end up in the general release sooner or later.

**Comment by burner1024** [comment]
you could try to run development version to see if you get a more descriptive message.

**Comment by burner1024** [comment]
I tried the insiders build, and it's not crashing for me, so see if you can narrow it down.

**Comment by ALIENQuake** [comment]
Those crashes are also gone for me. I've noticed that the Insiders build received several updates when I experienced those crashes so there is a high chance it's fixed. I'm closing the issue for now, if I will face the crashes again I will create a new one.
